/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125RouteImport } from './routes/{$restaurantUsername}-{$branchId}-{$tableNo}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RestaurantUsernameRouteImport } from './routes/$restaurantUsername'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as ETokenRouteImport } from './routes/e.$token'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as ApiImageProxyRouteImport } from './routes/api/image-proxy'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiBranchTablesRouteImport } from './routes/api/branch-tables'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminRestaurantsRouteImport } from './routes/admin/restaurants'
import { Route as AdminQrRouteImport } from './routes/admin/qr'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedWaiterPanelRouteImport } from './routes/_authenticated/waiter-panel'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRestaurantProfileRouteImport } from './routes/_authenticated/restaurant-profile'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedFoodItemsRouteImport } from './routes/_authenticated/food-items'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as BranchIdTableIdRouteImport } from './routes/$branchId.$tableId'
import { Route as RestaurantUsernameETokenRouteImport } from './routes/$restaurantUsername.e.$token'
import { Route as RestaurantUsernameBranchIdTableIdRouteImport } from './routes/$restaurantUsername.$branchId.$tableId'

const Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route =
  Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125RouteImport.update(
    {
      id: '/{$restaurantUsername}-{$branchId}-{$tableNo}',
      path: '/{$restaurantUsername}-{$branchId}-{$tableNo}',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantUsernameRoute = RestaurantUsernameRouteImport.update({
  id: '/$restaurantUsername',
  path: '/$restaurantUsername',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ETokenRoute = ETokenRouteImport.update({
  id: '/e/$token',
  path: '/e/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBranchTablesRoute = ApiBranchTablesRouteImport.update({
  id: '/api/branch-tables',
  path: '/api/branch-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWaiterPanelRoute =
  AuthenticatedWaiterPanelRouteImport.update({
    id: '/waiter-panel',
    path: '/waiter-panel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRestaurantProfileRoute =
  AuthenticatedRestaurantProfileRouteImport.update({
    id: '/restaurant-profile',
    path: '/restaurant-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodItemsRoute = AuthenticatedFoodItemsRouteImport.update({
  id: '/food-items',
  path: '/food-items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BranchIdTableIdRoute = BranchIdTableIdRouteImport.update({
  id: '/$branchId/$tableId',
  path: '/$branchId/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantUsernameETokenRoute =
  RestaurantUsernameETokenRouteImport.update({
    id: '/e/$token',
    path: '/e/$token',
    getParentRoute: () => RestaurantUsernameRoute,
  } as any)
const RestaurantUsernameBranchIdTableIdRoute =
  RestaurantUsernameBranchIdTableIdRouteImport.update({
    id: '/$branchId/$tableId',
    path: '/$branchId/$tableId',
    getParentRoute: () => RestaurantUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$restaurantUsername': typeof RestaurantUsernameRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$restaurantUsername}-{$branchId}-{$tableNo}': typeof Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route
  '/$branchId/$tableId': typeof BranchIdTableIdRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/food-items': typeof AuthenticatedFoodItemsRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/restaurant-profile': typeof AuthenticatedRestaurantProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/waiter-panel': typeof AuthenticatedWaiterPanelRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/branch-tables': typeof ApiBranchTablesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/e/$token': typeof ETokenRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/$restaurantUsername/$branchId/$tableId': typeof RestaurantUsernameBranchIdTableIdRoute
  '/$restaurantUsername/e/$token': typeof RestaurantUsernameETokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$restaurantUsername': typeof RestaurantUsernameRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$restaurantUsername}-{$branchId}-{$tableNo}': typeof Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route
  '/$branchId/$tableId': typeof BranchIdTableIdRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/food-items': typeof AuthenticatedFoodItemsRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/restaurant-profile': typeof AuthenticatedRestaurantProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/waiter-panel': typeof AuthenticatedWaiterPanelRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/branch-tables': typeof ApiBranchTablesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/e/$token': typeof ETokenRoute
  '/m/$slug': typeof MSlugRoute
  '/admin': typeof AdminIndexRoute
  '/$restaurantUsername/$branchId/$tableId': typeof RestaurantUsernameBranchIdTableIdRoute
  '/$restaurantUsername/e/$token': typeof RestaurantUsernameETokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$restaurantUsername': typeof RestaurantUsernameRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$restaurantUsername}-{$branchId}-{$tableNo}': typeof Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route
  '/$branchId/$tableId': typeof BranchIdTableIdRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/food-items': typeof AuthenticatedFoodItemsRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/restaurant-profile': typeof AuthenticatedRestaurantProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/waiter-panel': typeof AuthenticatedWaiterPanelRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/branch-tables': typeof ApiBranchTablesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/e/$token': typeof ETokenRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/$restaurantUsername/$branchId/$tableId': typeof RestaurantUsernameBranchIdTableIdRoute
  '/$restaurantUsername/e/$token': typeof RestaurantUsernameETokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$restaurantUsername'
    | '/admin'
    | '/admin-auth'
    | '/auth'
    | '/sitemap.xml'
    | '/{$restaurantUsername}-{$branchId}-{$tableNo}'
    | '/$branchId/$tableId'
    | '/analytics'
    | '/branches'
    | '/categories'
    | '/dashboard'
    | '/feedback'
    | '/food-items'
    | '/kitchen'
    | '/orders'
    | '/pos'
    | '/promotions'
    | '/reservations'
    | '/restaurant-profile'
    | '/settings'
    | '/staff'
    | '/subscription'
    | '/waiter-panel'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/qr'
    | '/admin/restaurants'
    | '/admin/revenue'
    | '/admin/seo'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/api/branch-tables'
    | '/api/health'
    | '/api/image-proxy'
    | '/api/realtime'
    | '/e/$token'
    | '/m/$slug'
    | '/admin/'
    | '/$restaurantUsername/$branchId/$tableId'
    | '/$restaurantUsername/e/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$restaurantUsername'
    | '/admin-auth'
    | '/auth'
    | '/sitemap.xml'
    | '/{$restaurantUsername}-{$branchId}-{$tableNo}'
    | '/$branchId/$tableId'
    | '/analytics'
    | '/branches'
    | '/categories'
    | '/dashboard'
    | '/feedback'
    | '/food-items'
    | '/kitchen'
    | '/orders'
    | '/pos'
    | '/promotions'
    | '/reservations'
    | '/restaurant-profile'
    | '/settings'
    | '/staff'
    | '/subscription'
    | '/waiter-panel'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/qr'
    | '/admin/restaurants'
    | '/admin/revenue'
    | '/admin/seo'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/api/branch-tables'
    | '/api/health'
    | '/api/image-proxy'
    | '/api/realtime'
    | '/e/$token'
    | '/m/$slug'
    | '/admin'
    | '/$restaurantUsername/$branchId/$tableId'
    | '/$restaurantUsername/e/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$restaurantUsername'
    | '/admin'
    | '/admin-auth'
    | '/auth'
    | '/sitemap.xml'
    | '/{$restaurantUsername}-{$branchId}-{$tableNo}'
    | '/$branchId/$tableId'
    | '/_authenticated/analytics'
    | '/_authenticated/branches'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/food-items'
    | '/_authenticated/kitchen'
    | '/_authenticated/orders'
    | '/_authenticated/pos'
    | '/_authenticated/promotions'
    | '/_authenticated/reservations'
    | '/_authenticated/restaurant-profile'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/subscription'
    | '/_authenticated/waiter-panel'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/qr'
    | '/admin/restaurants'
    | '/admin/revenue'
    | '/admin/seo'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/api/branch-tables'
    | '/api/health'
    | '/api/image-proxy'
    | '/api/realtime'
    | '/e/$token'
    | '/m/$slug'
    | '/admin/'
    | '/$restaurantUsername/$branchId/$tableId'
    | '/$restaurantUsername/e/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RestaurantUsernameRoute: typeof RestaurantUsernameRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminAuthRoute: typeof AdminAuthRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route: typeof Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route
  BranchIdTableIdRoute: typeof BranchIdTableIdRoute
  ApiBranchTablesRoute: typeof ApiBranchTablesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ETokenRoute: typeof ETokenRoute
  MSlugRoute: typeof MSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$restaurantUsername}-{$branchId}-{$tableNo}': {
      id: '/{$restaurantUsername}-{$branchId}-{$tableNo}'
      path: '/{$restaurantUsername}-{$branchId}-{$tableNo}'
      fullPath: '/{$restaurantUsername}-{$branchId}-{$tableNo}'
      preLoaderRoute: typeof Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$restaurantUsername': {
      id: '/$restaurantUsername'
      path: '/$restaurantUsername'
      fullPath: '/$restaurantUsername'
      preLoaderRoute: typeof RestaurantUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$token': {
      id: '/e/$token'
      path: '/e/$token'
      fullPath: '/e/$token'
      preLoaderRoute: typeof ETokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branch-tables': {
      id: '/api/branch-tables'
      path: '/api/branch-tables'
      fullPath: '/api/branch-tables'
      preLoaderRoute: typeof ApiBranchTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qr': {
      id: '/admin/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/waiter-panel': {
      id: '/_authenticated/waiter-panel'
      path: '/waiter-panel'
      fullPath: '/waiter-panel'
      preLoaderRoute: typeof AuthenticatedWaiterPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurant-profile': {
      id: '/_authenticated/restaurant-profile'
      path: '/restaurant-profile'
      fullPath: '/restaurant-profile'
      preLoaderRoute: typeof AuthenticatedRestaurantProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food-items': {
      id: '/_authenticated/food-items'
      path: '/food-items'
      fullPath: '/food-items'
      preLoaderRoute: typeof AuthenticatedFoodItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$branchId/$tableId': {
      id: '/$branchId/$tableId'
      path: '/$branchId/$tableId'
      fullPath: '/$branchId/$tableId'
      preLoaderRoute: typeof BranchIdTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$restaurantUsername/e/$token': {
      id: '/$restaurantUsername/e/$token'
      path: '/e/$token'
      fullPath: '/$restaurantUsername/e/$token'
      preLoaderRoute: typeof RestaurantUsernameETokenRouteImport
      parentRoute: typeof RestaurantUsernameRoute
    }
    '/$restaurantUsername/$branchId/$tableId': {
      id: '/$restaurantUsername/$branchId/$tableId'
      path: '/$branchId/$tableId'
      fullPath: '/$restaurantUsername/$branchId/$tableId'
      preLoaderRoute: typeof RestaurantUsernameBranchIdTableIdRouteImport
      parentRoute: typeof RestaurantUsernameRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedFoodItemsRoute: typeof AuthenticatedFoodItemsRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedRestaurantProfileRoute: typeof AuthenticatedRestaurantProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedWaiterPanelRoute: typeof AuthenticatedWaiterPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedFoodItemsRoute: AuthenticatedFoodItemsRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedRestaurantProfileRoute: AuthenticatedRestaurantProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedWaiterPanelRoute: AuthenticatedWaiterPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RestaurantUsernameRouteChildren {
  RestaurantUsernameBranchIdTableIdRoute: typeof RestaurantUsernameBranchIdTableIdRoute
  RestaurantUsernameETokenRoute: typeof RestaurantUsernameETokenRoute
}

const RestaurantUsernameRouteChildren: RestaurantUsernameRouteChildren = {
  RestaurantUsernameBranchIdTableIdRoute:
    RestaurantUsernameBranchIdTableIdRoute,
  RestaurantUsernameETokenRoute: RestaurantUsernameETokenRoute,
}

const RestaurantUsernameRouteWithChildren =
  RestaurantUsernameRoute._addFileChildren(RestaurantUsernameRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminQrRoute: typeof AdminQrRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminQrRoute: AdminQrRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RestaurantUsernameRoute: RestaurantUsernameRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminAuthRoute: AdminAuthRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route:
    Char123restaurantUsernameChar125Char123branchIdChar125Char123tableNoChar125Route,
  BranchIdTableIdRoute: BranchIdTableIdRoute,
  ApiBranchTablesRoute: ApiBranchTablesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ETokenRoute: ETokenRoute,
  MSlugRoute: MSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
